name: Release app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Zip app
        run: zip -r app.zip dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get commit hash
        id: commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        with:
          tag_name: ${{ steps.commit-hash.outputs.commit-hash }}
          release_name: Release ${{ steps.commit-hash.outputs.commit-hash }}
          body: |
            Release ${{ steps.commit-hash.outputs.commit-hash }} has been created automatically.

          draft: false
          prerelease: false
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        with:
            files: app.zip
            tag_name: ${{ steps.commit-hash.outputs.commit-hash }}
            name: app.zip